spring:
  profiles:
    active: dev
---
spring:
  port: 3355
  profiles: dev
  application:
    name: cloud-config-client-dev
eureka:
  instance:
    instance-id: cloud-config-client
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://139.9.211.150:7001/eureka/,http://139.9.211.150:7002/eureka/,http://139.9.211.150:7003/eureka/
---
spring:
  port: 3355
  profiles: prop
  application:
    name: cloud-config-client-prop
eureka:
  instance:
    instance-id: cloud-config-client
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://139.9.211.150:7001/eureka/,http://139.9.211.150:7002/eureka/,http://139.9.211.150:7003/eureka/
